type ArrayOf9 = [
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
  number | undefined,
];

export type BoardType = [
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
  ArrayOf9,
];

export type PossibilitiesType = (number[] | undefined)[][];

export const defaultBoard: BoardType = [
  [0, 0, 5, 0, 7, 8, 0, 0, 9],
  [0, 8, 0, 0, 0, 0, 0, 0, 0],
  [2, 7, 0, 0, 0, 0, 1, 0, 0],
  [0, 0, 0, 0, 0, 0, 2, 4, 3],
  [1, 9, 0, 7, 0, 0, 0, 0, 5],
  [0, 0, 0, 3, 0, 0, 0, 0, 0],
  [0, 4, 0, 0, 0, 1, 0, 0, 0],
  [0, 0, 0, 8, 0, 5, 0, 0, 7],
  [3, 0, 0, 0, 0, 0, 9, 0, 0],
];

export const emptyBoard: BoardType = [
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
  [
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined,
  ],
];
